title:       "Zabbix public templates"
header_title: "Zabbix public templates"
email:       your@ema.il
author:      Your Name
description: "My blog description"
baseurl:     ""
url:         "https://myblog.com"
date_format: "%-d.%m.%Y"

collections:
  zabbix_templates:
      output: true
      permalink: /templates/:name/